### ISSUE TITLE
[feature request] thermal_zone and CPU frequency device as settings

### ISSUE THREAD

**Issue by kylehase** [Sennevds/system_sensors#105]
This is a great script but it could be made more portable if a few hard-coded values were pulled out as settings.

`get_temp()` is hard coded to use `thermal_zone0` and `get_clock_speed()` is hard coded to use `/sys/devices/cpu/cpu0/cpufreq/scaling_cur_freq`. On my Ubuntu NUC, the CPU temp is `thermal_zone2` and CPU frequency is `/sys/devices/cpu/cpufreq/policy0/scaling_cur_freq`. I've updated my local script to use these values but ideally they should be settings to provide the greatest portability.

```yaml
sensors:
  temperature: true
    # ignored for rasp OSs
    zone: thermal_zone2 # defaults to thermal_zone0
  clock_speed: true
    # ignored for rasp OSs
    device: /sys/devices/cpu/cpufreq/policy0/scaling_cur_freq # defaults to /sys/devices/cpu/cpu0/cpufreq/scaling_cur_freq
```

I tried to create a patch and pull request for this but the sensor functions are called in a too clever way, which makes passing arguments difficult for someone with my limited Python experience.
