### ISSUE TITLE
External Drives fail

### ISSUE THREAD

**Issue by boskoe** [Sennevds/system_sensors#116]
Hi,

I've spent around 10 hours trying to sort this out on my own and now I have to throw in the towel.

I have a Raspberry Pi 4, 8 GB setup as an IOT server. For the most part everything is working and 
system_sensors is working well except for External Drives.  

If you could give some advise or clues as to what might be the problem I would be greatful.

Oh and I just cloned the latest repo this morning.

Thanks,

Doug

About my installation:

uname -a
`Linux iot64 5.10.63-v8+ #1459 SMP PREEMPT Wed Oct 6 16:42:49 BST 2021 aarch64 GNU/Linux`

settings.yaml
`mqtt:
  hostname: IOT64
  port: 1883 #defaults to 1883
  user: user
  password: password
deviceName: IOT64
client_id: IOT64
timezone: someplace
update_interval: 60 #Defaults to 60
sensors:
  temperature: true
  clock_speed: true
  disk_use: true
  memory_use: true
  cpu_usage: true
  load_1m: true
  load_5m: true
  load_15m: true
  net_tx: true
  net_rx: true
  swap_usage: true
  power_status: true
  last_boot: true
  hostname: true
  host_ip: true
  host_os: true
  host_arch: true
  last_message: true
  updates: true
  wifi_strength: false
  wifi_ssid: false
external_drives:
  Images: /media/pi/IMAGES/`

Launching system_sensors
`~/system_sensors $ python3 src/system_sensors.py src/settings.yaml
send config message
Connected to broker
`

I get this in MQTT
`{"name":"IOT64 Disk Use","state_topic":"system-sensors/sensor/iot64/state","unit_of_measurement":"%","value_template":"{{value_json.disk_use}}","unique_id":"iot64_sensor_disk_use","availability_topic":"system-sensors/sensor/iot64/availability","device":{"identifiers":["iot64_sensor"],"name":"IOT64 Sensors","model":"RPI IOT64", "manufacturer":"RPI"},"icon":"mdi:micro-sd"}`

I get this in Home Assistant
![image](https://user-images.githubusercontent.com/10463052/140103347-edc8f4c8-4a99-4ecb-bfef-219bf1392bdd.png)

**Comment by Sennevds** [comment]
Hi, could you format your settings.yaml?

**Comment by boskoe** [comment]
Hi,

I thought I did. Doesn't <Insert code> do that?

**Comment by Sennevds** [comment]
![image](https://user-images.githubusercontent.com/3531609/140512878-31eb5460-098a-48ed-804e-0c67fffca55b.png)
this isn't formatted :) I want to check if the indentation is right

**Comment by boskoe** [comment]
Sennevds,

I'm trying to post it formatted but can't find how to do that. I tried the insert code tag and that produced what you see.

Could you please tell me how to escape the yaml I'm trying to paste?

Thanks

**Comment by boskoe** [comment]
I think I found it.

```mqtt:
  hostname: somehost
  port: 1883 #defaults to 1883
  user: someuser
  password: somepassword
deviceName: IOT64
client_id: IOT64
timezone: SomeTimeZone
update_interval: 60 #Defaults to 60
sensors:
  temperature: true
  clock_speed: true
  disk_use: true
  memory_use: true
  cpu_usage: true
  load_1m: true
  load_5m: true
  load_15m: true
  net_tx: true
  net_rx: true
  swap_usage: true
  power_status: true
  last_boot: true
  hostname: true
  host_ip: true
  host_os: true
  host_arch: true
  last_message: true
  updates: true
external_drives:
  images: /media/pi/IMAGES/ ```

**Comment by Sennevds** [comment]
If you're on the latest master version you need to indent external_drives like this:
```
mqtt:
  hostname: somehost
  port: 1883 #defaults to 1883
  user: someuser
  password: somepassword
deviceName: IOT64
client_id: IOT64
timezone: SomeTimeZone
update_interval: 60 #Defaults to 60
sensors:
  temperature: true
  clock_speed: true
  disk_use: true
  memory_use: true
  cpu_usage: true
  load_1m: true
  load_5m: true
  load_15m: true
  net_tx: true
  net_rx: true
  swap_usage: true
  power_status: true
  last_boot: true
  hostname: true
  host_ip: true
  host_os: true
  host_arch: true
  last_message: true
  updates: true
  external_drives:
    images: /media/pi/IMAGES/ 
```
