### ISSUE TITLE
[Need Help] Reporting on external SSD

### ISSUE THREAD

**Issue by raviwarrier** [Sennevds/system_sensors#119]
This is similar to #75 but since that was closed without resolution...

This used to work before, but somehow I can't make it work after I reformatted+reinstalled my pi.

Here an image of the result of blkid:
![image](https://user-images.githubusercontent.com/42061703/142636262-fda8f3dc-2ce9-4319-aa06-22f80430ac4d.png)

My external SSD is mounted as '/dev/sda1' is accessed by '/srv/dev-disk-by-uuid-E4FAC652FAC62122/'.

I have tried everything '/dev/sd1', '/dev/disk/by-uuid/E4FAC652FAC62122' (i don't know, but I saw this on Webmin's dashboard) and '/srv/dev-disk-by-uuid-E4FAC652FAC62122/', but everything gives out 0% or Unavailable or Unknown.

I also have a problem with my /boot (used to work before the clean install) and tried permutations of that as well.

Please help. Also, you had asked for this in #75 and I would gladly give it only if I understood what that was and how to get it.

Thanks.

**Comment by Sennevds** [comment]
Do you get any error and could you send your config?

**Comment by raviwarrier** [comment]
I get no error when I run the service.
![image](https://user-images.githubusercontent.com/42061703/142640063-536aedbd-2836-4649-8827-fcb2b83beb53.png)

pi@rwpi:~ $ cat system_sensors/src/settings.yaml
mqtt:
  hostname: 192.168.1.14
  port: 1883 #defaults to 1883
  user: ****
  password: ********
deviceName: RWPI
client_id: RWPI_SS
timezone: Asia/Kolkata
update_interval: 60 #Defaults to 60
sensors:
  temperature: true
  clock_speed: true
  disk_use: true
  memory_use: true
  cpu_usage: true
  load_1m: true
  load_5m: true
  load_15m: true
  net_tx: true
  net_rx: true
  swap_usage: true
  power_status: true
  last_boot: true
  hostname: true
  host_ip: true
  host_os: true
  host_arch: true
  last_message: true
  updates: true
  wifi_strength: true
  wifi_ssid: true
  external_drives:
    # Only add mounted drives here, e.g.:
    # Drive1: /media/storage
    SSD: /srv/dev-disk-by-uuid-E4FAC652FAC62122/
    SDCard: /boot/

I hope I sent you the correct info.

**Comment by raviwarrier** [comment]
Here's the screenshot from HA for the SSD:

![image](https://user-images.githubusercontent.com/42061703/142640370-e6cd5016-4dd6-461f-9aab-87e298b2c858.png)

**Comment by Sennevds** [comment]
> I get no error when I run the service. ![image](https://user-images.githubusercontent.com/42061703/142640063-536aedbd-2836-4649-8827-fcb2b83beb53.png)
> 
> pi@rwpi:~ $ cat system_sensors/src/settings.yaml mqtt: hostname: 192.168.1.14 port: 1883 #defaults to 1883 user: **** password: ******** deviceName: RWPI client_id: RWPI_SS timezone: Asia/Kolkata update_interval: 60 #Defaults to 60 sensors: temperature: true clock_speed: true disk_use: true memory_use: true cpu_usage: true load_1m: true load_5m: true load_15m: true net_tx: true net_rx: true swap_usage: true power_status: true last_boot: true hostname: true host_ip: true host_os: true host_arch: true last_message: true updates: true wifi_strength: true wifi_ssid: true external_drives: # Only add mounted drives here, e.g.: # Drive1: /media/storage SSD: /srv/dev-disk-by-uuid-E4FAC652FAC62122/ SDCard: /boot/
> 
> I hope I sent you the correct info.
> 
> Edit: the spacing under external_drives: is as per your example, but it's not showing up here.

Could you format the config so I can see that is right intended (https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)

What do you get when you run sudo systemctl status system_sensors

**Comment by raviwarrier** [comment]
trying. if this doesn't work, will upload the yaml file and share the link

```yaml
mqtt:
  hostname: 192.168.1.14
  port: 1883 #defaults to 1883
  user: admin
  password: g4QtJ$0pbc
deviceName: RWPI
client_id: RWPI_SS
timezone: Asia/Kolkata
update_interval: 60 #Defaults to 60
sensors:
  temperature: true
  clock_speed: true
  disk_use: true
  memory_use: true
  cpu_usage: true
  load_1m: true
  load_5m: true
  load_15m: true
  net_tx: true
  net_rx: true
  swap_usage: true
  power_status: true
  last_boot: true
  hostname: true
  host_ip: true
  host_os: true
  host_arch: true
  last_message: true
  updates: true
  wifi_strength: true
  wifi_ssid: true
  external_drives:
    # Only add mounted drives here, e.g.:
    # Drive1: /media/storage
    SSD: /srv/dev-disk-by-uuid-E4FAC652FAC62122/
    SDCard: /boot/
```
