### ISSUE TITLE
SyntaxError: File "system_sensors.py", line 74

### ISSUE THREAD

**Issue by nortuzar** [Sennevds/system_sensors#40]
Hi, I'm trying to use this on a raspberry 3a+ on volumio music software. I was able to install all the dependencies but when I run the command `python3 system_sensors.py /path/to/settings.yaml` I recieve the following error
```
volumio@eltemploport:~/system_sensors/src$ python3 system_sensors.py settings.yaml
  File "system_sensors.py", line 74
    print (f"Message received: {message.payload.decode()}"  )
```
This is the settings.yaml config
```
mqtt:
  hostname: 192.168.1.4
  port: 1883 #defaults to 1883
  user: mqtt
  password: xxxxxxx
deviceName: volumio
client_id: mqtt
timezone: America/Santiago
power_integer_state: false #defaults to false
update_interval: 60 #Defaults to 60
check_wifi_strength: true
check_available_updates: true
external_drives:
  Drive1: /boot/
```

Any advice to solve this? 

Thanks!
