### ISSUE TITLE
LastBoot as relative time?

### ISSUE THREAD

**Issue by mrBrutus** [Sennevds/system_sensors#50]
First a big thanks for creating this as it creates a really nice overview of my Raspi's.

Can you please share how you got the relative time format (`3 days ago`) for `LastBoot` in your example?
In my Home Assistant it is shown absolute like `2020-08-24T19:43:25+02:00`. 

I got it working a bit using below template but maybe there is a better way (this one does not update on page refresh).

```yaml
  - platform: template
    sensors:
      control_center_uptime: 
        friendly_name: Uptime
        value_template: '{{ relative_time(strptime(states.sensor.control_center_lastboot.state, "%Y-%m-%dT%H:%M:%S%z")) }}'
```

**Comment by Sennevds** [comment]
Normally it should come as relative time format when you place it in lovelace.
Does the entity has timestamp as device_class?

**Comment by mrBrutus** [comment]
After setting up a new Home Assistant from scratch and inserting the entities in Lovelace it still showed up as absolute times.

I now solved it after learning about [Customizing entities](https://www.home-assistant.io/docs/configuration/customizing-devices) and some inspiration found in [klaasnicolaas/Student-homeassistant-config](https://github.com/klaasnicolaas/Student-homeassistant-config): 

1. Create a *global customization* file e.g. `/customizations/global/sensor.yaml`:
   ```yaml
   # show <system_sensors> time stamps as relative time
   sensor.*_lastboot:
     device_class: timestamp
   
   sensor.*_lastmessage:
     device_class: timestamp
   ```
1. Enable the customization in `configuration.yaml`:
   ```yaml
   homeassistant:
     # Customize individual entities
     customize: !include_dir_merge_named customizations/entities
     # Customize all entities in a domain
     customize_domain: !include_dir_merge_named customizations/domains
     # Customize entities matching a pattern
     customize_glob: !include_dir_merge_named customizations/global
   ```
