### ISSUE TITLE
Unavailable entities because of availability topic stays offline (Home Assistant / yaml mode)

### ISSUE THREAD

**Issue by septeven** [Sennevds/system_sensors#57]
Hi,

I have noticed a problem (I'm pretty sure this occurs when restarting HA) with entities being unavailable until I stop and start again the service on the pi zero itself.

I checked out with MQTT Explorer and realized that is because the `availability` topic stays `offline`, while the `state` topic keep being updated. 

For now, as a workaround, I have commented the line related to the availability in my yaml (yes I'm using yaml instead of auto-discovery), but any chance you let me know if that can be fixed by your side ? 
See an example of my yaml:
```yaml
    - platform: mqtt
      name: "Pizero Office Temperature"
      state_topic: "system-sensors/sensor/pizero-office/state"
      # availability_topic: "system-sensors/sensor/pizero-office/availability"
      # payload_available: "online"
      # payload_not_available: "offline"
      value_template: "{{ value_json.temperature }}"
      device_class: temperature
      unit_of_measurement: '°C'
      icon: mdi:thermometer
```
Thanks ;)
