### ISSUE TITLE
Maybe a custom component

### ISSUE THREAD

**Issue by bboti86** [Sennevds/system_sensors#71]
Hi, 
I keep thinking that it would be so great to have all of the info available from the PI that runs home assistant as well. 

Could this be a custom component of Home Assistant or an add-on for Hass.IO maybe? 

Thanks! 
B

**Comment by MaxVRAM** [comment]
Hi @bboti86 - you might want to look at Home Assistant's own [System Monitor](https://www.home-assistant.io/integrations/systemmonitor) integration, which exposes a very similar scope of system monitoring values.

It's very easy to set up. You just add a few lines in your configuration.yaml

For an example, this is what I have in my own HA config:

```
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
      - type: memory_use_percent
      - type: processor_use
      - type: processor_temperature
      - type: last_boot
      - type: throughput_network_in
        arg: 'eth0'
      - type: throughput_network_out
        arg: 'eth0'
```

Hope that helps. Unless there's something specific you're after that's missing from HA's integration, this issue could be closed.
