### ISSUE TITLE
Failed to start system-sensor.service: Unit system-sensor.service not found.

### ISSUE THREAD

**Issue by flex-0** [Sennevds/system_sensors#77]
Hey there,

I installed the script on my pihole rpi3b. 

I autostarted the script but didn't see anything in Hass so I checked the status:

`flex0@pihole:~ $ sudo systemctl status system_sensors.service
● system_sensors.service - System Sensor service
   Loaded: loaded (/etc/systemd/system/system_sensors.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Wed 2021-01-13 18:40:10 CET; 30min ago
 Main PID: 2252 (code=exited, status=0/SUCCESS)

Jan 13 18:40:10 pihole systemd[1]: Started System Sensor service.
Jan 13 18:40:10 pihole python3[2252]: Timezone not defined in settings.yaml! Please check the documentation
Jan 13 18:40:10 pihole systemd[1]: system_sensors.service: Succeeded.`

So because the servic was dead I started the script manualy:

`flex0@pihole:~ $ systemctl start system-sensor.service
==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ===
Authentication is required to start 'system-sensor.service'.
Multiple identities can be used for authentication:
 1.  ,,, (pi)
 2.  ,,, (flex0)
Choose identity to authenticate as (1-2): 2
Password: 
==== AUTHENTICATION COMPLETE ===
Failed to start system-sensor.service: Unit system-sensor.service not found.
flex0@pihole:~ $ sudo systemctl status system_sensors.service
`
It states that the Unit is not found, but I have no idea what to do from here on. Any thoughts on that? I Checked the isues but couldnt find anything that helped. I'm just starting to get along with linux and Hass so sorry if this turns out to be obviously easy to solve by my self.

**Comment by Sennevds** [comment]
Did you read the first error?
```log
Jan 13 18:40:10 pihole python3[2252]: Timezone not defined in settings.yaml! Please check the documentation
```
You need to change the settings.yaml according the installation notes: https://github.com/Sennevds/system_sensors#installation
The second error is because you tried to start the service system-sensors instead of the service system_sensors

**Comment by flex-0** [comment]
Yes I did, I also changed the timezone a few times while always getting the same error. If this is the reason for the failure I'm not sure what I'm doing wrong.  Filling in the timezone from a predefined list cant be that hard but obviously I'm stupid ;-) 

Here is my settings.yaml, do you see a mistake there? 

mqtt:
   hostname: 192.168.178.12
   port: 1883
   user: username
   password: mypassword
   deviceName: pihole
   client_id: pihole
   timezone: Europe/Berlin
   update_interval: 60 #Defaults to 60
   check_wifi_strength: false
   check_available_updates: true
   external_drives:
   Drive1: /boot/

**Comment by Sennevds** [comment]
Could you send the system_sensor.service file?

**Comment by flex-0** [comment]
[Unit]
Description=System Sensor service
After=multi-user.target

[Service]
User=flex0
Type=idle
ExecStart=/usr/bin/python3 /home/flex0/system_sensors/src/system_sensors.py /home/flex0/system_sensors/src/settings.yaml

[Install]
WantedBy=multi-user.target

**Comment by Sennevds** [comment]
Could you format your settings.yaml file? because now I can't see if your indents are right.
Also did you retry to start the service by executing the folowing command:
`` sudo systemctl start system_sensors.service``
?

**Comment by flex-0** [comment]
`
mqtt:
  hostname: 192.168.178.12
  port: 1883
  user: homeassistant
  password: Ceith4Cohr1gazuabei3eeYee6aephix8zeHiobeziuVaib6toh9Igoo7Shuo6ye
  deviceName: pihole
  client_id: pihole
  timezone: Europe/Berlin
  update_interval: 60 #Defaults to 60
  check_wifi_strength: false
  check_available_updates: true
  external_drives:
  Drive1: /boot/


`

**Comment by flex-0** [comment]
Yes, I started it new, but the error is the same as before Active (Dead) and timezone. Here is the formatted config.yaml, I hope I did it right

```
mqtt:
   hostname: 192.a.x.y
   port: 1883
   user: username
   password: mypassword
   deviceName: pihole
   client_id: pihole
   timezone: Europe/Berlin
   update_interval: 60 #Defaults to 60
   check_wifi_strength: false
   check_available_updates: true
   external_drives:
   Drive1: /boot/
```

**Comment by Sennevds** [comment]
your indents are wrong it should look like this
```yaml
mqtt:
    hostname: 192.a.x.y
    port: 1883
    user: username
    password: mypassword
deviceName: pihole
client_id: pihole
timezone: Europe/Berlin
update_interval: 60 #Defaults to 60
check_wifi_strength: false
check_available_updates: true
external_drives:
    Drive1: /boot/
```
